"""Trajectory rollout and cost evaluation for Box-iLQR."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, TypeAlias

import numpy as np

from boxilqr.barriers import (
    evaluate_box_barrier,
    expand_barrier_parameters,
)
from boxilqr.options import ScalarOrArray
from boxilqr.problem import Array, Bounds, BoxILQRProblem


ControlPolicy: TypeAlias = Callable[[Array, int], Array]


@dataclass(frozen=True)
class TrajectoryCost:
    """Components of a trajectory's total cost."""

    running_cost: float
    terminal_cost: float
    state_barrier_cost: float
    control_barrier_cost: float

    @property
    def original_cost(self) -> float:
        """Cost without logarithmic barriers."""

        return self.running_cost + self.terminal_cost

    @property
    def barrier_cost(self) -> float:
        """Total state and control barrier cost."""

        return (
            self.state_barrier_cost
            + self.control_barrier_cost
        )

    @property
    def total_cost(self) -> float:
        """Barrier-augmented trajectory cost."""

        return self.original_cost + self.barrier_cost


@dataclass(frozen=True)
class RolloutResult:
    """State-control trajectory generated by a rollout."""

    states: Array
    controls: Array
    cost: TrajectoryCost

    def __post_init__(self) -> None:
        states = np.asarray(self.states, dtype=float)
        controls = np.asarray(self.controls, dtype=float)

        if states.ndim != 2:
            raise ValueError("states must be a two-dimensional array.")

        if controls.ndim != 2:
            raise ValueError("controls must be a two-dimensional array.")

        if states.shape[0] != controls.shape[0] + 1:
            raise ValueError(
                "The state trajectory must contain one more point "
                "than the control trajectory."
            )

        if not np.all(np.isfinite(states)):
            raise ValueError("states contains non-finite values.")

        if not np.all(np.isfinite(controls)):
            raise ValueError("controls contains non-finite values.")

        object.__setattr__(self, "states", states.copy())
        object.__setattr__(self, "controls", controls.copy())

    @property
    def total_cost(self) -> float:
        """Barrier-augmented trajectory cost."""

        return self.cost.total_cost

    @property
    def original_cost(self) -> float:
        """Trajectory cost without barriers."""

        return self.cost.original_cost

    @property
    def barrier_cost(self) -> float:
        """Total logarithmic-barrier cost."""

        return self.cost.barrier_cost


def _prepare_parameters(
    bounds: Bounds | None,
    parameters: ScalarOrArray | None,
    dimension: int,
    name: str,
) -> Array | None:
    """Prepare barrier parameters when finite constraints exist."""

    if bounds is None or not bounds.has_constraints:
        return None

    if parameters is None:
        raise ValueError(
            f"{name} must be provided because finite bounds are present."
        )

    return expand_barrier_parameters(
        parameters,
        dimension,
        name=name,
    )


def rollout_policy(
    problem: BoxILQRProblem,
    initial_state: Array,
    policy: ControlPolicy,
    *,
    state_barrier: ScalarOrArray | None = None,
    control_barrier: ScalarOrArray | None = None,
    minimum_margin: float = 1.0e-12,
) -> RolloutResult:
    """Roll out a time-varying control policy.

    The policy must have the signature

        control = policy(state, k).
    """

    if not callable(policy):
        raise TypeError("policy must be callable.")

    initial_state = problem.validate_state(initial_state)

    state_parameters = _prepare_parameters(
        problem.state_bounds,
        state_barrier,
        problem.state_dim,
        "state_barrier",
    )

    control_parameters = _prepare_parameters(
        problem.control_bounds,
        control_barrier,
        problem.control_dim,
        "control_barrier",
    )

    states = np.zeros(
        (problem.horizon + 1, problem.state_dim),
        dtype=float,
    )

    controls = np.zeros(
        (problem.horizon, problem.control_dim),
        dtype=float,
    )

    states[0] = initial_state

    running_cost = 0.0
    terminal_cost = 0.0
    state_barrier_cost = 0.0
    control_barrier_cost = 0.0

    for k in range(problem.horizon):
        current_state = states[k]

        if state_parameters is not None:
            state_evaluation = evaluate_box_barrier(
                value=current_state,
                bounds=problem.state_bounds,
                parameters=state_parameters,
                minimum_margin=minimum_margin,
                variable_name=f"state at time {k}",
            )

            state_barrier_cost += state_evaluation.value

        current_control = policy(
            current_state.copy(),
            k,
        )

        current_control = problem.validate_control(
            current_control
        )

        controls[k] = current_control

        if control_parameters is not None:
            control_evaluation = evaluate_box_barrier(
                value=current_control,
                bounds=problem.control_bounds,
                parameters=control_parameters,
                minimum_margin=minimum_margin,
                variable_name=f"control at time {k}",
            )

            control_barrier_cost += control_evaluation.value

        running_cost += problem.evaluate_running_cost(
            current_state,
            current_control,
            k,
        )

        states[k + 1] = problem.step(
            current_state,
            current_control,
            k,
        )

    terminal_state = states[-1]

    if state_parameters is not None:
        terminal_barrier = evaluate_box_barrier(
            value=terminal_state,
            bounds=problem.state_bounds,
            parameters=state_parameters,
            minimum_margin=minimum_margin,
            variable_name=f"terminal state at time {problem.horizon}",
        )

        state_barrier_cost += terminal_barrier.value

    terminal_cost = problem.evaluate_terminal_cost(
        terminal_state
    )

    trajectory_cost = TrajectoryCost(
        running_cost=float(running_cost),
        terminal_cost=float(terminal_cost),
        state_barrier_cost=float(state_barrier_cost),
        control_barrier_cost=float(control_barrier_cost),
    )

    if not np.isfinite(trajectory_cost.total_cost):
        raise ValueError(
            "The trajectory produced a non-finite total cost."
        )

    return RolloutResult(
        states=states,
        controls=controls,
        cost=trajectory_cost,
    )


def rollout(
    problem: BoxILQRProblem,
    initial_state: Array,
    controls: Array,
    *,
    state_barrier: ScalarOrArray | None = None,
    control_barrier: ScalarOrArray | None = None,
    minimum_margin: float = 1.0e-12,
) -> RolloutResult:
    """Roll out a supplied open-loop control trajectory."""

    controls = np.asarray(controls, dtype=float)

    expected_shape = (
        problem.horizon,
        problem.control_dim,
    )

    if controls.shape != expected_shape:
        raise ValueError(
            f"controls must have shape {expected_shape}, "
            f"but received {controls.shape}."
        )

    if not np.all(np.isfinite(controls)):
        raise ValueError(
            "controls must contain only finite values."
        )

    def open_loop_policy(
        state: Array,
        k: int,
    ) -> Array:
        del state
        return controls[k]

    return rollout_policy(
        problem=problem,
        initial_state=initial_state,
        policy=open_loop_policy,
        state_barrier=state_barrier,
        control_barrier=control_barrier,
        minimum_margin=minimum_margin,
    )
